(ns tiltontec.testing
  (:require
            ;[tiltontec.test.evaluate :refer [run-tests] :as test-eval]
            ;[tiltontec.test.observer :refer [run-tests] :as test-obs]
            ;[tiltontec.test.integrity :refer [run-tests] :as test-integ]
            ;[tiltontec.test.lazy-cells :refer [run-tests] :as test-lazy]
            [tiltontec.test.cell-core :refer [run-tests] :as test-cell-core]))

(defn run-tests []
  ;(test-eval/run-tests)
  ;(test-obs/run-tests)
  ;(test-integ/run-tests)
  ;(test-lazy/run-tests)
  (test-cell-core/run-tests)
  (prn :testing-OK))
